version: '3'
services:
  redis:
    image: redis:latest
  api:
    build:
      context: ./server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    stdin_open: true
    build:
      context: ./client
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'