version: '3'

services:
  redis:
    container_name: redis 
    image: redis:latest
  postgres:
    container_name: postgres    
    image: postgres:latest
    environment:
      - POSTGRES_USER=jake
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=personal_project
  api:
    container_name: api
    build:
      context: ./server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=jake
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=personal_project
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - redis
      - postgres
  client:
    container_name: client
    stdin_open: true
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client