version: '3'
services:
  redis:
    image: redis:latest
  api:
    build:
      context: ./server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    stdin_open: true
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'