version: '3'
services:
  redis:
    image: redis:latest
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=jake
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=personal_project
  api:
    build:
      context: ./server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=jake
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=personal_project
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - redis
      - postgres
  client:
    stdin_open: true
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"